name: binder-test
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - pandas
    - matplotlib
    - numpydoc
    - pandocfilter
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
